apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        test: c1
    spec:
      containers:
      - image: bettylu/echo-server:latest
        name: myapp
        ports:
        - containerPort: 8080
