apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        test: c1
    spec:
      containers:
      - image: {{ .Values.image }}
        name: myapp
        env:
        - name: aliyun_logs_{{ .Values.log.key }} # 采集方式
          value: stdout
        - name: aliyun_logs_{{ .Values.log.key }}_tags  # 日志标识
          value: app=echo
        ports:
        - containerPort: 8080
