apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        test: c1
    spec:
      containers:
      - image: {{ .Values.image }}
        name: myapp
        ports:
        - containerPort: 8080
